### ISSUE TITLE
GetProcAddress of ordinal 100 fails for XInput 9.1.0

### ISSUE THREAD

**Issue by hymerman** [speps/XInputDotNet#16]
It looks like getting ordinal 100 doesn't work for XInput 9.1.0 and that getting "XInputGetState" should be used instead (that's speculation; correct me if I'm wrong). This could be done as a backup for if ordinal 100 fails. But of course, the whole point of doing it the way it's done is to expose the guide button, and silently picking a version of the function that doesn't report the guide button seems quite nasty. Any idea how to get around this?

I created this issue to track part of the discussion started here:
https://github.com/speps/XInputDotNet/commit/ae1c0a9057c2d99a2e1118032934a74daa6fb05e#commitcomment-10177512

**Comment by hymerman** [comment]
Something like this is what I mean:

    if(!mGetState)
    {
        // Getting 'ordinal 100' will apparently fail if xinput9_1_0.dll was loaded. Fall back to XInputGetState instead, which should succeed but won't 
        mGetState = (XInputGetStatePointer)GetProcAddress(mHandle, "XInputGetState");
    }

**Comment by speps** [comment]
I don't know how the ordinal 100 was found in xinput1_3.dll but I guess stepping though the assembly might give a clue. I suspect they would mask out the guide button bits somewhere. So it might be another ordinal for xinput9_1_0.dll.
