### ISSUE TITLE
Dlls are conflicting

### ISSUE THREAD

**Issue by UserAnon91** [speps/XInputDotNet#17]
Using the unity package I imported XInput into my project roughly a three months ago.  Since then, our project has switched to Unity 5 and although we thought we were prepared for conflicts and potential breaking, we couldn't get XInput to function.  I'm getting this error;

<code>Plugin 'XInputInterface.dll' is used from several locations:
 Assets/Plugins/x86/XInputInterface.dll would be copied to <PluginPath>/XInputInterface.dll
 Assets/Plugins/x86_64/XInputInterface.dll would be copied to <PluginPath>/XInputInterface.dll
Plugin 'XInputDotNetPure.dll' is used from several locations:
 Assets/Plugins/x86_64/XInputDotNetPure.dll would be copied to <PluginPath>/XInputDotNetPure.dll
 Assets/Plugins/x86/XInputDotNetPure.dll would be copied to <PluginPath>/XInputDotNetPure.dll
Please fix plugin settings and try again.</code>

<code>
UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()
</code>

Not sure if there's a quick fix, but it's stopping us from doing web builds, which are currently needed.

Cheers,
-James Gudge

**Comment by speps** [comment]
I don't think you can do both native plugins and web builds.

About the problem you have, I didn't check if the plugin works in Unity 5 yet, but I will soon although I can't guarantee when. I'm doing this on my free time and it's a free plugin :)

**Comment by mvdklip** [comment]
Two thoughts:
1) Have you tried messing around with the new [Plugin Inspector](http://docs.unity3d.com/Manual/PluginInspector.html)?
2) XInputDotNetPure.dll is a managed plugin which should not be in Plugins/x86 and Plugins/x86_64. Instead either the x86 or the x86_64 dll (depending on a 32 vs 64 bit Unity editor) should be copied directly in Plugins. Otherwise this DLL will be treated like a native plugin and included in builds which is not needed.

**Comment by speps** [comment]
Thanks, I started reading how the new plugin stuff works in Unity 5. However, I've yet to try it :)

**Comment by speps** [comment]
I've fixed this by upgrading the project to Unity 5. However I found that the plugin settings can sometimes be lost so the readme now contains examples of how to set them up.
