### ISSUE TITLE
Xbox One Controller vibrations don't work as expected

### ISSUE THREAD

**Issue by hersheys72** [speps/XInputDotNet#22]
Hi,

Thank you for the plug in :)

I have run the example project in Unity 5.3.1 and the controller vibration doesn't seem to work properly. 

When run in Unity the right trigger vibrate works ok, but the left trigger does nothing. 
When running a "Build" version, the vibration is very delayed- and only again for the right trigger?

**Comment by ip0p** [comment]
Hi,

I have similar problems with the left trigger, BUT here with a xbox one controller. It works delayed in editor but not in build. All other functions work as they should. Also tested a 360 controller wich works fine.

**Comment by speps** [comment]
Yeah it would make sense that it doesn't work with an Xbox One controller. I never tried, but I don't think the API maps really well to it given that the vibrations now come from the triggers. I'll try to investigate at some point but I can't promise when.
