### ISSUE TITLE
Correct the calling conversion in gamepad.h

### ISSUE THREAD

**Issue by frozenology** [speps/XInputDotNet#26]
I tried to run the project and debugger got a error with calling conversion.
so i added WINAPI directive to gamepad.h to fix.

typedef DWORD (WINAPI *XInputGetStatePointer)(DWORD dwUserIndex, XINPUT_STATE* pState);
typedef DWORD (WINAPI *XInputSetStatePointer)(DWORD dwUserIndex, XINPUT_VIBRATION* pVibration);

**Comment by speps** [comment]
Thanks, a PR would help here. It's simple enough to modify by hand on GitHub yourself without having to fork the whole repo.

**Comment by speps** [comment]
Fixed by ef10076
