### ISSUE TITLE
Steamworks issues

### ISSUE THREAD

**Issue by cor2879** [speps/XInputDotNet#38]
Hello, I'm developing a game in Unity and using XInputDotNet to access the rumble feature of the Xbox One gamepad.  I integrated it into my game months ago and it has always worked great.  However recently I added Steamworks to my game (since it is going to be released on Steam).  Now the rumble feature just doesn't work.  I'm sure the problem is on the Steamworks side, nevertheless I am curious if anyone has encountered this issue before and has some insight on how to deal with it?

Thanks!

**Comment by speps** [comment]
It would be useful to know if there is any DLL loading issue. Have you checked Unity's log when you run your game with Steamworks enabled?

**Comment by cor2879** [comment]
No I haven't.  Sorry to sound ignorant but where exactly can I find that?

**Comment by speps** [comment]
https://docs.unity3d.com/Manual/LogFiles.html

The Player section has some info, including how to change the log location if needed.

**Comment by cor2879** [comment]
Awesome, thanks!

**Comment by speps** [comment]
Let me know what you find as it might help others.

**Comment by cor2879** [comment]
I definitely will.  Hopefully I’ll have some time this evening to look into
it.

**Comment by cor2879** [comment]
I took a look at the log and definitely did not see anything that stood out regarding assemblies not loading.  I have had a few things recommended to try on the Steamworks forum that I'm going to try.  I'll update if I find something that helps.

**Comment by cor2879** [comment]
So this is interesting.  I decided to take a look at the GamepadState for PlayerIndex.One (actually I did all the player indexes just for kicks) and they all indicate false, which means XInput isn't even detecting the gamepad.

**Comment by cor2879** [comment]
Hi, still working with some people in the Steam forums on this issue.  What version of XInput is currently being targeted by XInputDotNet?

**Comment by speps** [comment]
It should work 1.3, 1.4 and 9.1.0: https://github.com/speps/XInputDotNet/blob/00e2b6b71afc7d42326249a058b43b3abf08f189/XInputInterface/GamePad.cpp#L26

**Comment by cor2879** [comment]
Hi, thank you for your support.  So I finally found the issue.  It's was not XInput in any way as far as I can tell.  Basically, the batteries in my gamepad were low and it must have turned off vibration to conserve power.  After I changed the batteries it started working again.  Sorry for the trouble but hopefully if anyone else has a similar problem they'll see this.

**Comment by speps** [comment]
Haha nice find! Invest in a corded one for development, it's slightly better for the environment ;)
