### ISSUE TITLE
What is XInputDotNetPure

### ISSUE THREAD

**Issue by CyberFoxHax** [speps/XInputDotNet#40]
I had it in my projects for years, i don't remember where i found it. Today i wanted to find the source. But all i can find is your repo. Do you know what's going on?

**Comment by speps** [comment]
The source is there: https://github.com/speps/XInputDotNet/tree/master/XInputDotNetPure. It's part of the project, it's the Unity side DLL that then loads the XInputInterface DLL to actually do the internal XInput calls.

**Comment by CyberFoxHax** [comment]
Yeah ok thanks
